### fogot pass
PUT http://localhost:8000/api/user-management/forgot-password
Content-Type: application/json
Accept: application/json
 
{
     "email":"phuocsanhtps@gmail.com"
}

### register
POST http://localhost:8000/api/user-management/register
Content-Type: application/json
Accept: application/json
 
{
     "email":"phuocsanhqstapaas@gmail.com"
}

### change pass
PUT http://localhost:8000/api/user-management/change-password
Content-Type: application/json
Accept: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTdmMDBlZGE4NDU3NDI0NDE3YjE2YyIsImlhdCI6MTY1OTM2ODMzMywiZXhwIjoxNjU5NDExNTMzfQ.vthV7pk__-3yWEzZVzHt9klxt_sQqbJaqt8spvb11PY"

{
     "password":"Of2$5l&hG6pgKgNb",
     "password_New":"SanhTp$123456"
}

### searchReview
GET http://localhost:8000/api/review-management/search-review?ebookId=62e9fd003aa42835a6f8f182
Content-Type: application/json
Accept: application/json

### search chapter
GET http://localhost:8000/api/chapter-management/search-chapter?ebookId=62e9fd003aa42835a6f8f182
Content-Type: application/json
Accept: application/json

