### fogot pass
PUT http://localhost:8000/api/user-management/forgot-password
Content-Type: application/json
Accept: application/json
 
{
     "email":"phuocsanhtps@gmail.com"
}

### change pass
PUT http://localhost:8000/api/user-management/change-password
Content-Type: application/json
Accept: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTdmMDBlZGE4NDU3NDI0NDE3YjE2YyIsImlhdCI6MTY1OTM2ODIwNywiZXhwIjoxNjU5NDExNDA3fQ.CP7GcDZmTy2zbQ4QsxKY5oP6oQZE-Xb4kkvA8CO5870"

{
     "password":"Of2$5l&hG6pgKgNb",
     "password_New":"SanhTp$123456"
}